apiVersion: apps/v1
kind: Deployment
metadata:
  name: term-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: term-project
  template:
    metadata:
      labels:
        app: term-project
    spec:
      containers:
      - name: term-project
        image: term-project:latest
        imagePullPolicy: Never  # Important for local images
        ports:
        - containerPort: 3000