apiVersion: apps/v1
kind: Deployment
metadata:
  name: term-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: term-project
  template:
    metadata:
      labels:
        app: term-project
    spec:
      containers:
      - name: term-project
        image: madushanka92/term-project:latest  # Docker Hub image
        imagePullPolicy: Always  # Ensure the image is pulled from Docker Hub on every deployment
        ports:
        - containerPort: 3000
