name: CI Workflow

on:
  push:
    branches:
      - master   # Runs on push to the master branch
  pull_request:
    branches:
      - master   # Runs on PR merge to master branch

jobs:
  test:
    runs-on: ubuntu-latest  # OS where the tests 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the appropriate Node.js version (e.g., 16.x)

      - name: Install dependencies
        run: npm install  # Installs the dependencies defined in package.json

      - name: Run tests
        run: npm test  # Runs the tests using the "test" script in the package.json

