name: CI Workflow

on:
  push:
    branches:
      - master   # Runs on push to the master branch
  pull_request:
    branches:
      - master   # Runs on PR merge to master branch

jobs:
  test:
    runs-on: ubuntu-latest  # OS where the tests run
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the appropriate Node.js version (e.g., 16.x)

      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm install  # Installs the dependencies defined in package.json

      - name: Run tests
        run: npm run test  # Runs the tests using the "test" script in the package.json

      - name: Trigger Jenkins after workflow success
        if: success()
        run: |
          curl -X POST https://cb26-2607-fea8-4ee1-8100-59a4-2bc8-c135-b9cb.ngrok-free.app/job/TriggerWithGIT/build \
          --user suminda:11ec73e022d566d8dfa9d66483fb0d5122
